### PR TITLE
suppress desktop_notification error

### PR DESCRIPTION
**Pull request by hunglin**
follow the example in #44 and add desktop_notification slack event.

@gilbertw1 , i included @sammyrulez's #44 changes in this PR.  so, you can just merge this one instead of merging both.  It can save you some conflict resolving effort.

### CODE REVIEW

**Comment by hunglin** [comment]
@gilbertw1 @sammyrulez, please review

**Comment by sammyrulez** [comment]
thanks!

**Comment by sammyrulez** [comment]
My changes are ok . Merge is "go" for me.

**Comment by zifeo** [comment]
@gilbertw1 What is the current status of this?

**Comment by gilbertw1** [comment]
Hey guys, sorry for the long delay! I've tested and merged these changes, and will get them out in a 0.2.1 release tomorrow.

Thanks for the contribution and your patience!

**Pull request merged**
